{{- if not .Values.config.key.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "broker-api.fullname" . }}
  labels:
    {{- include "broker-api.labels" . | nindent 4 }}
data:
  signing-key: {{ required "Please provide a value for .Values.config.key.signingKey To generate one, check: https://github.com/chainflip-io/chainflip-mainnet-apis?tab=readme-ov-file#generating-keys" .Values.config.key.signingKey | b64enc | quote }}
{{- end }}
