apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "chainflip-prometheus-exporter.fullname" . }}"
  labels: {{ include "chainflip-prometheus-exporter.labels" . | nindent 4 }}
spec:
  replicas: 1
  {{- if .Values.persistentVolumes }}
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels: {{ include "chainflip-prometheus-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: "{{ include "chainflip-prometheus-exporter.fullname" . }}"
      {{- if not .Values.config.existingConfigMap }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
      {{- end }}
      labels: {{ include "chainflip-prometheus-exporter.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: "{{ include "chainflip-prometheus-exporter.fullname" . }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
              name: metrics
          {{- if .Values.secret.getEnvFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.secret.getEnvFromSecret }}
                optional: false
          {{- else }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /usr/src/app/config.json
              subPath: config.json
              name: config
            {{- range .Values.persistentVolumes }}
            - name: {{ required "persistentVolumes[].name is required" .name }}
              mountPath: {{ required "persistentVolumes[].mountPath is required" .mountPath }}
              {{- with .subPath }}
              subPath: {{ . }}
              {{- end }}
              {{- if .readOnly }}
              readOnly: true
              {{- end }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            optional: false
            {{- if .Values.config.existingConfigMap }}
            name: {{ .Values.config.existingConfigMap }}
            {{- else }}
            name: {{ include "chainflip-prometheus-exporter.fullname" . }}
            {{- end }}
        {{- range .Values.persistentVolumes }}
        - name: {{ required "persistentVolumes[].name is required" .name }}
          persistentVolumeClaim:
            claimName: {{ required "persistentVolumes[].name is required" .name }}
        {{- end }}

