{{- range .Values.persistentVolumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ required "persistentVolumes[].name is required" .name }}
  labels:
    {{- include "chainflip-prometheus-exporter.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml (.accessModes | default (list "ReadWriteOnce")) | nindent 4 }}
  {{- with .storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ required "persistentVolumes[].size is required" .size | quote }}
{{- end }}