{{- if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") .Values.node.ports.metrics.enabled .Values.node.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "chainflip-node.fullname" . }}
  {{- with .Values.node.serviceMonitor.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "chainflip-node.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      {{- with .Values.node.serviceMonitor.path }}
      path: {{ . }}
      {{- end }}
      {{- with .Values.node.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.node.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.node.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.node.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
